{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"files.associations": {
			"*.json": "cpp",
			"*.ejs": "html",
			"": "",
			"iostream": "cpp"
		},
		"search.exclude": {
			"**/*.o": true,
			"**/*.su": true,
			"**/*.cmd": true
		},
		"files.exclude": {
			"**/*.o": true,
			"**/*.su": true,
			"**/*.cmd": true
		}
	}
}